### ISSUE TITLE
Is this plugin still maintained?

### ISSUE THREAD

**Issue by t-kietzmann** [gatsby-uc/gatsby-source-strapi#352] opened 2022-11-01 15:38 UTC
Till now it's not possible with the official package release to use Gatsby (using it on Gatsby Cloud) with Strapi in production, cause build fails at least with empty RichText fields. 

Are there any plans to fix those issues in the near future?

**Comment by keegankb93** [comment] 2022-11-01 17:58
The empty text is fixed in the alpha version mentioned here: https://github.com/strapi/gatsby-source-strapi/issues/321

However, that comes with its own problems regarding image extraction. 

I do have the same concerns with the plugin being maintained though.

**Comment by t-kietzmann** [comment] 2022-11-01 18:35
it would be good to know what the plans are. right now i have to leave either gatsby or strapi, neither would be nice

**Comment by altonalexander** [comment] 2022-11-02 11:51
I too had a similar concern but was able to get it working perfectly by:

1) install by using the hotfix alpha version or another developer's fork to fix some of the latest bugs.
2) in development mode make sure your strapi has data in every field then take a snapshot of the schema for production using the plugin gatsby-plugin-schema-snapshot. Be sure to turn off the schema generation in production using the options described (update: process.env.GATSBY_UPDATE_SCHEMA_SNAPSHOT == "true")

That said, I love the open source community and am grateful for these contributions that make it possible to do our work. I would like to see a release bump asap so that users don't have to go hunting for the hot fix. Cheers.

**Comment by derrickmehaffy** [comment] 2022-11-02 15:21
Hey all, we have shared this issue with the team to try and get an answer, once we have something we will share it.

**Comment by MotaZor94** [comment] 2022-11-08 11:42
Hey @derrickmehaffy , do we have any updates on this one? We are currently stuck in a middle of a project due to the fact that the richText is null in preview mode.

**Comment by laurenskling** [comment] 2022-11-08 19:39
I'm happy to see more people are on the bandwagon. Really hoping we can create some momentum for the team to do a new development cycle on this.

In the mean while, the 2.1.0 alpha fixed the rich content but broke image relations. I fixed it at https://github.com/strapi/gatsby-source-strapi/pull/348, I've been running this commit for a while now in production and it get's the source plugin back into the modern world! 

For those who do not want to use anything but the official releases. Turn off cloud builds, it will do a full data source every time, including working rich content. All you need is lots of patience 💤

**Comment by MotaZor94** [comment] 2022-11-08 20:04
@t-kietzmann , I'll probably stick with Strapi. I have this love and hate relationship with it. 
I just hope this will be fixed as soon as possible (soon as possible as in TOMORROW would be ideal), we have a client sitting on our head and waiting for a project to be finished. I just feel like everything I do that is gatsby-strapi related ends up being some hacky stuff that I need to ask people around and ask why it isn't working as it's supposed to be. It's like that for the past 3 years and it's starting to get on my nerves. But I guess I get it, there are other priorities.

**Comment by derrickmehaffy** [comment] 2022-11-09 20:35
Small update, we are still discussing in the team at the moment. I don't have anything to share for now but the convo has been raised and some solutions are being discussed.

**Comment by MotaZor94** [comment] 2022-11-28 12:55
Hi @derrickmehaffy, any updates?

**Comment by kalwas123** [comment] 2022-12-05 10:30
@derrickmehaffy, any updates?

**Comment by kalwas123** [comment] 2022-12-05 10:31
@derrickmehaffy, any updates?

**Comment by derrickmehaffy** [comment] 2022-12-12 23:01
Apologies everyone I was out on vacation for 2 weeks. I've added this to my to do to check in with our product engineering teams to confirm.

Unofficially I believe our intention is to transfer this repo to a different maintainer as it's unlikely that we will continue to maintain it ourselves. Again treat this as unofficial until I confirmed it, ideally we want to reach out to the Gatsby team to see if they are willing to take up maintainership of it themselves but in lieu of that we would be willing to transfer it over to someone else.

Currently our team lacks the capacity to effectively maintain this ourselves and it also goes against our agnostic approach to front-end frameworks. Are in goal would be to create a generic JavaScript SDK that would work on any front end not just something like Gatsby. It puts us in a precarious position to maintain something that only affects a single front end framework and goes against our agnostic nature.

---

Again please allow me to confirm what the team as the above is just my personal opinion not the opinion or position of Strapi itself.

**Comment by Aurelsicoko** [comment] 2022-12-13 17:20
I confirm what @derrickmehaffy previously shared with you, we can't maintain this integration ourselves anymore; we lack the bandwidth and internal resources, and it hasn't been identified as a priority. We are looking for new maintainers, and we would like to start the discussion with the Community Organization to see if it's something they could help us with 😊

_Note: you can consider my message as a final decision on our end_

**Comment by moonmeister** [comment] 2022-12-15 18:58
@Aurelsicoko Hey! I started the [Gatsby User Collective](https://gatsbyuc.dev/) for cases just like this. @laurenskling has offed to help maintain the plugin if we can bring it into the Gatsby UC. I'd love to make it possible for the community to continue maintaining this plugin into the future, If you're interested in moving forward, please open an [issue](https://github.com/gatsby-uc/plugins/issues/new?assignees=moonmeister&labels=new-plugin&template=submit-plugin.yml&title=add%5Bplugin-name%5D).

**Comment by derrickmehaffy** [comment] 2022-12-15 19:03
> @Aurelsicoko Hey! I started the [Gatsby User Collective](https://gatsbyuc.dev/) for cases just like this. @laurenskling has offed to help maintain the plugin if we can bring it into the Gatsby UC. I'd love to make it possible for the community to continue maintaining this plugin into the future, If you're interested in moving forward, please open an [issue](https://github.com/gatsby-uc/plugins/issues/new?assignees=moonmeister&labels=new-plugin&template=submit-plugin.yml&title=add%5Bplugin-name%5D).

This is absolutely awesome to hear! Tomorrow morning I'll get the issue created and start preparing to see if we can transfer the repo and npm package if it's approved. @laurenskling  is a very familiar face to us and has been around the Strapi community for a long time, I would love to see him as a maintainer!

**Comment by laurenskling** [comment] 2022-12-15 19:06
Thanks for the trust @derrickmehaffy <3
I hope the UC would be a good place for this, where everyone in need of this package can get involved. I hope that won't just be me ;)

**Comment by moonmeister** [comment] 2022-12-15 19:09
@derrickmehaffy - Awesome to hear! First steps are listed below. The repo transfer also requires the person doing the transfer be added to the GUC organization. I'll get that setup for you and @Aurelsicoko. This will allow y'all to contribute in the future as well should you ever want to do so.  

- [ ] [transfer the repo](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-user-account) to the `gatsby-uc` organization.
- [ ] [Add `moonmeister` as a maintainer](https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account) on your npm package.

**Comment by derrickmehaffy** [comment] 2022-12-15 19:10
> Thanks for the trust @derrickmehaffy <3
> I hope the UC would be a good place for this, where everyone in need of this package can get involved. I hope that won't just be me ;)

Of course, this is exactly the same reason we help fund/found the Strapi community org as well. It's easier when you have quite a few people willing to help step in and assist. Certainly I think even some devs from the Strapi team would be willing to put in some PRs in the future as well.

We just couldn't plan anything in the short term as other higher priority stuff has come up that needs our focus and we didn't want people to have to wait on us to move in the project.

**Comment by derrickmehaffy** [comment] 2022-12-15 19:11
I'll double check with the team but I see zero problems with us transferring to the Gatsby UC, I just want to dot all the Is and cross all the Ts :)

**Comment by derrickmehaffy** [comment] 2022-12-15 19:17
> @derrickmehaffy - Awesome to hear! First steps are listed below. The repo transfer also requires the person doing the transfer be added to the GUC organization. I'll get that setup for you and @Aurelsicoko. This will allow y'all to contribute in the future as well should you ever want to do so.  
> 
> - [ ] [transfer the repo](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-user-account) to the `gatsby-uc` organization.
> - [ ] [Add `moonmeister` as a maintainer](https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account) on your npm package. 

Sounds good thank you. I'll probably wait til next week just in case anyone in our team has a protest but I highly doubt that will be an issue.

I may need to have you add a different person instead of @Aurelsicoko and instead make that @alexandrebodin as he is our CTO and main admin on GitHub who will likely assist me in the transfer (he is also our main admin on NPM too).

**Comment by moonmeister** [comment] 2022-12-15 19:19
> I may need to have you add a different person instead of @Aurelsicoko and instead make that @alexandrebodin as he is our CTO and main admin on GitHub who will likely assist me in the transfer (he is also our main admin on NPM too).

done. 

P.S. my philosophy is that you all have whatever access you want. I don't normally remove your NPM access and I'm happy to add whatever teammebers to the GUC team as maintainers so y'all can work on the plugin if needed.

**Comment by derrickmehaffy** [comment] 2022-12-15 19:25
> > I may need to have you add a different person instead of @Aurelsicoko and instead make that @alexandrebodin as he is our CTO and main admin on GitHub who will likely assist me in the transfer (he is also our main admin on NPM too).
> 
> done. 
> 
> P.S. my philosophy is that you all have whatever access you want. I don't normally remove your NPM access and I'm happy to add whatever teammebers to the GUC team as maintainers so y'all can work on the plugin if needed. 

Awesome to hear, thanks again and I'm very happy to see this going into a well known community focus organization.

**Comment by romanslonov** [comment] 2022-12-16 17:02
Will this plugin be updated for version gatsby v5? Or what's the alternatives?

**Comment by jonadeline** [comment] 2022-12-19 06:23
@romanslonov Im using it with Gatsby v5 and so far it's working.

**Comment by romanslonov** [comment] 2022-12-19 07:43
@jonadeline Interesting. How did you solve this issue?

```
gatsby-strapi on  main via  v18.12.1
❯ npm i gatsby-source-strapi
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: gatsby-starter-default@0.1.0
npm ERR! Found: gatsby@5.3.2
npm ERR! node_modules/gatsby
npm ERR!   gatsby@"^5.3.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer gatsby@"^4.0.0" from gatsby-source-strapi@2.0.0
npm ERR! node_modules/gatsby-source-strapi
npm ERR!   gatsby-source-strapi@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by jonadeline** [comment] 2022-12-19 08:12
@romanslonov I force the resolution using `npm install --force` 
in my CI/CD pipeline I dont have the issue as `npm ci` must include the force option by default.

**Comment by derrickmehaffy** [comment] 2022-12-20 19:18
I've created the issue here: https://github.com/gatsby-uc/plugins/issues/330 and will start working on our tasks to get things moved over!

**Comment by laurenskling** [comment] 2022-12-22 09:51
Thanks @derrickmehaffy , i will try to find the time asap to work on this :) Thanks again for the trust in me and hope we can work together on the plugin in the future :)

**Comment by moonmeister** [comment] 2022-12-27 17:57
Thanks for your interest in this project. This plugin has moved into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to implement fixes or features, or join us on [Discord](discord.gg/gwnqfzetjv) if you have questions!

**Closed by moonmeister** 2022-12-27 17:57 UTC
Labels: status: help wanted
